const {readFileSync} = require('node:fs');
const {runInNewContext} = require('node:vm');
const assert = require('node:assert/strict');
const checks = runInNewContext(`${readFileSync(`${__dirname}/diagnostics.js`, 'utf8')}\ndiagnosticChecks`);
const healthy = {reachable:true,statusCode:200,latencyMs:2,detail:null};
const snapshot = () => ({relay:{live:healthy,ready:healthy,sponsorBalanceMicroStx:'100',minimumBalanceMicroStx:'10',quotesEnabled:true,sponsorshipsEnabled:true},node:{health:healthy,referenceHealth:healthy,fullySynced:true,stacksTipHeight:123,referenceTipHeight:123,blocksBehind:0}});
assert.ok(checks(snapshot()).every(check => check.state === 'pass'));
const low = snapshot();
low.relay.sponsorBalanceMicroStx = '9007199254740992';
low.relay.minimumBalanceMicroStx = '9007199254740993';
low.relay.ready = {...healthy,reachable:false,statusCode:503};
assert.match(checks(low).find(check => check.title === 'Relay readiness').action, /testnet STX/);
assert.equal(checks(low).find(check => check.title === 'Sponsor funding').state, 'fail');
const upstream = snapshot();
upstream.relay.ready = {...healthy,reachable:false,statusCode:503};
upstream.relay.sponsorBalanceMicroStx = null;
assert.match(checks(upstream).find(check => check.title === 'Relay readiness').action, /upstream/);
assert.equal(checks(upstream).find(check => check.title === 'Sponsor funding').state, 'warn');
const offline = snapshot(); offline.relay.live = {...healthy,reachable:false}; offline.relay.ready = offline.relay.live;
assert.match(checks(offline).find(check => check.title === 'Relay readiness').action, /liveness first/);
const reference = snapshot(); reference.node.referenceHealth = {...healthy,reachable:false}; reference.node.blocksBehind = null;
assert.equal(checks(reference).find(check => check.title === 'Public reference').state, 'warn');
assert.equal(checks(reference).find(check => check.title === 'Relay readiness').state, 'pass');
const sync = snapshot(); sync.node.fullySynced = null;
assert.match(checks(sync).find(check => check.title === 'Follower synchronization').evidence, /did not report/);
sync.node.health = {...healthy,reachable:false}; sync.node.fullySynced = true;
assert.equal(checks(sync).find(check => check.title === 'Follower synchronization').state, 'warn');
console.log('Diagnostics recommendation tests passed.');
